version: "2.4"
services:
  reverse_proxy:
    image: matcha_reverse_proxy
    container_name: matcha_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - matcha_network
    depends_on:
      - server
      - ui

  ui:
    image: matcha_ui
    container_name: matcha_ui
    build:
      context: ui
    mem_limit: 1g
    networks:
      - matcha_network
    depends_on:
      - server

  server:
    image: matcha_server
    container_name: matcha_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - matcha_network
    depends_on:
      - mongodb
    environment:
      - MATCHA_MONGODB_URI=mongodb://mongodb:27017/matcha?retryWrites=true&w=majority
      - MATCHA_ELASTICSEARCH_NODE=http://elasticsearch:9200

  mongodb:
    image: mongo:4.2.13-bionic
    container_name: matcha_mongodb
    restart: unless-stopped
    networks:
      - matcha_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: matcha_elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - network.host=0.0.0.0
    mem_limit: 1g
    networks:
      - matcha_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    container_name: matcha_kibana
    depends_on:
      - elasticsearch
    networks:
      - matcha_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

networks:
  matcha_network:
    name: matcha_network
